/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppBody {
        "value": string;
    }
    interface AppDivider {
        "color": string;
    }
    interface AppHeader {
        "value": string;
    }
}
declare global {
    interface HTMLAppBodyElement extends Components.AppBody, HTMLStencilElement {
    }
    var HTMLAppBodyElement: {
        prototype: HTMLAppBodyElement;
        new (): HTMLAppBodyElement;
    };
    interface HTMLAppDividerElement extends Components.AppDivider, HTMLStencilElement {
    }
    var HTMLAppDividerElement: {
        prototype: HTMLAppDividerElement;
        new (): HTMLAppDividerElement;
    };
    interface HTMLAppHeaderElement extends Components.AppHeader, HTMLStencilElement {
    }
    var HTMLAppHeaderElement: {
        prototype: HTMLAppHeaderElement;
        new (): HTMLAppHeaderElement;
    };
    interface HTMLElementTagNameMap {
        "app-body": HTMLAppBodyElement;
        "app-divider": HTMLAppDividerElement;
        "app-header": HTMLAppHeaderElement;
    }
}
declare namespace LocalJSX {
    interface AppBody {
        "value"?: string;
    }
    interface AppDivider {
        "color"?: string;
    }
    interface AppHeader {
        "value"?: string;
    }
    interface IntrinsicElements {
        "app-body": AppBody;
        "app-divider": AppDivider;
        "app-header": AppHeader;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-body": LocalJSX.AppBody & JSXBase.HTMLAttributes<HTMLAppBodyElement>;
            "app-divider": LocalJSX.AppDivider & JSXBase.HTMLAttributes<HTMLAppDividerElement>;
            "app-header": LocalJSX.AppHeader & JSXBase.HTMLAttributes<HTMLAppHeaderElement>;
        }
    }
}
